import { test } from "../../fixtures/businessFixture";
test('Verify the business home page', async ({ businessAccountHomePage,resisterPersonalDetailsPage,registerDateOfBirthPage,registerPersonalAddressPage,nationalityAndTaxPage,exitAccountcheckPage,registerSicAllResultPage }) => {
    await businessAccountHomePage.verifyPageTitle();
    await businessAccountHomePage.clickGetABusinessAccountLink();
    await businessAccountHomePage.clickOpenBusinessAccountLink();
    await businessAccountHomePage.clickSoleTraderLink();
    await businessAccountHomePage.clickAnnualTurnoverLink();
    await businessAccountHomePage.clickAnnualTurnoverContinueButton();
    await businessAccountHomePage.NextExpectContinueButton();
    await businessAccountHomePage.enterEmailAddress('itsarchana13+37@outlook.com');
    await businessAccountHomePage.clickSendCodeButton();
    await businessAccountHomePage.clickEmailPasscodeContinueButton();
    await businessAccountHomePage.enterMobileNumber('07435472433');
    await businessAccountHomePage.clickMobileSendCodeButton();
    await businessAccountHomePage.clickMobilePasscodeContinueButton();
    await businessAccountHomePage.enterSoleTraderName('archana Kumari');
    await businessAccountHomePage.clickSoleTraderCheckbox();
    await businessAccountHomePage.clickSoleTraderContinueButton();
    await businessAccountHomePage.clickApplyForBusinessAccountLink();
    await businessAccountHomePage.verifyLetGoTitle();
    await businessAccountHomePage.clickLetGoContinueButton();
    //await businessAccountHomePage.waitForPop();
    await businessAccountHomePage.clickSavingYourApplicationContinueButton();
    await resisterPersonalDetailsPage.enterPersonalDetails('Mr','Archana','Kumari','Singh');
    await registerDateOfBirthPage.enterDateOfBirth('01','01','1990');
    await registerPersonalAddressPage.enterRegisterPersonalAddress('10','IG1 2FJ','FLAT 90, ICON BUILDING, 39 ILFORD HILL, ILFORD');
    await registerPersonalAddressPage.clickConfirmAddressButton();
    await registerPersonalAddressPage.clickContinueButton();
    await nationalityAndTaxPage.nationalityAndTax();
    await exitAccountcheckPage.exitAccountCheck();
    await registerSicAllResultPage.clickSearchTheList();
});
